<a href="https://colab.research.google.com/github/dronmorse/Data_Science_Bootcamp/blob/main/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

### Norma wektora, długość wektora w R^2



In [3]:
v1 = np.array([1, 4])
v1

array([1, 4])

In [4]:
np.linalg.norm(v1)

4.123105625617661

### Norma euklidesowa w R^n

In [5]:
v2 = np.array([-10, 10, 13])

In [7]:
np.linalg.norm(v2)

19.209372712298546

### Odległość dwóch punktów na płaszczyźnie

### Odległość dwóch punktów w przestrzeni R^n

In [8]:
  p = np.array([3, 0])

In [9]:
q = np.array([0, 4])

In [11]:
np.linalg.norm(p - q)

5.0

In [14]:
  p = np.array([3, 0, 1])

In [13]:
q = np.array([0, 4, 2])

In [15]:
np.linalg.norm(p - q)

5.0990195135927845

### Mnożenie macierzy

In [20]:
 X = np.array([[5, 3],
               [3, 9]])
 Y = np.array([[1],
               [-1]])
 print(X)
 print(Y)

[[5 3]
 [3 9]]
[[ 1]
 [-1]]


In [21]:
Z = np.dot(X, Y)

In [22]:
print(Z)

[[ 2]
 [-6]]


In [24]:
Z.shape

(2, 1)

In [27]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])

In [28]:
Z = np.dot(X, Y)

In [29]:
print(Z)

[[13  9 -4]
 [ 6  2 -1]]


### Wyznacznik macierzy

In [32]:
 A = np. array([[2, 4],
                [-1, 3]])

In [34]:
round(np.linalg.det(A))

10

### Ślad macierzy

In [42]:
 A = np.array([[2, 4, 3],
                [-1, 3, 2],
                [5, 4, 9]])

In [41]:
np.trace(A)

14

### Macierz jednostkowa

In [43]:
I = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])

In [45]:
i = np.eye(3, dtype='int')

In [47]:
print(I)
print(i)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


### Macierz odwrotna
AB = BA = I

In [48]:
A = np.array([[2, 4],
              [-1, 3]])

In [50]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [55]:
np.set_printoptions(precision=4, suppress=True)

np.dot(A, B)
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

### Macierz transponowana

wiersz = kolumna, kolumna = wiersz

In [56]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [57]:
A.T

array([[ 2, -1],
       [ 4,  3]])