<a href="https://colab.research.google.com/github/dronmorse/Data_Science_Bootcamp/blob/main/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

### Norma wektora, długość wektora w R^2



In [3]:
v1 = np.array([1, 4])
v1

array([1, 4])

In [4]:
np.linalg.norm(v1)

4.123105625617661

### Norma euklidesowa w R^n

In [5]:
v2 = np.array([-10, 10, 13])

In [6]:
np.linalg.norm(v2)

19.209372712298546

### Odległość dwóch punktów na płaszczyźnie

### Odległość dwóch punktów w przestrzeni R^n

In [7]:
  p = np.array([3, 0])

In [8]:
q = np.array([0, 4])

In [9]:
np.linalg.norm(p - q)

5.0

In [10]:
  p = np.array([3, 0, 1])

In [11]:
q = np.array([0, 4, 2])

In [12]:
np.linalg.norm(p - q)

5.0990195135927845

### Mnożenie macierzy

In [13]:
 X = np.array([[5, 3],
               [3, 9]])
 Y = np.array([[1],
               [-1]])
 print(X)
 print(Y)

[[5 3]
 [3 9]]
[[ 1]
 [-1]]


In [14]:
Z = np.dot(X, Y)

In [15]:
print(Z)

[[ 2]
 [-6]]


In [16]:
Z.shape

(2, 1)

In [17]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])

In [18]:
Z = np.dot(X, Y)

In [19]:
print(Z)

[[13  9 -4]
 [ 6  2 -1]]


### Wyznacznik macierzy

In [20]:
 A = np. array([[2, 4],
                [-1, 3]])

In [21]:
round(np.linalg.det(A))

10

### Ślad macierzy

In [22]:
 A = np.array([[2, 4, 3],
                [-1, 3, 2],
                [5, 4, 9]])

In [23]:
np.trace(A)

14

### Macierz jednostkowa

In [24]:
I = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])

In [25]:
i = np.eye(3, dtype='int')

In [26]:
print(I)
print(i)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


### Macierz odwrotna
AB = BA = I

In [27]:
A = np.array([[2, 4],
              [-1, 3]])

In [28]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [29]:
np.set_printoptions(precision=4, suppress=True)

np.dot(A, B)
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

### Macierz transponowana

wiersz = kolumna, kolumna = wiersz

In [30]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [31]:
A.T

array([[ 2, -1],
       [ 4,  3]])

### Rozwiązywanie układu równań
### jeżeli macierz jest kwadratowa to AX = B -> A^-1*AX = A^-1B -> X = A^-1B

In [51]:
 C = np.array([[2, 4],
               [1, -1]])
 print(C)

[[ 2  4]
 [ 1 -1]]


In [54]:
W = np.array([[10],
             [-1]])
print(W)

[[10]
 [-1]]


In [55]:
C_inv = np.linalg.inv(C)
X = np.dot(C_inv, W)
X

array([[1.],
       [2.]])