<a href="https://colab.research.google.com/github/dronmorse/Data_Science_Bootcamp/blob/main/1_ds_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install numpy

In [3]:
import numpy as np
np.__version__

'1.23.5'

In [4]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 

In [5]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

### 1D ARRAY

In [6]:
x = np.array([1, 3])
print(x)
type(x)

[1 3]


numpy.ndarray

In [7]:
x

array([1, 3])

In [8]:
x.ndim

1

In [9]:
x.shape

(2,)

In [10]:
x.size

2

In [11]:
x.dtype

dtype('int64')

In [12]:
y= np.array([1.3, 2.3, 1.4])

In [13]:
print(y)

[1.3 2.3 1.4]


In [14]:
y.dtype

dtype('float64')

### 2D ARRAY

In [15]:
z = np.array([[1, 3],
             [-1, 1]])

In [16]:
print(z)

[[ 1  3]
 [-1  1]]


In [17]:
z.ndim

2

In [18]:
z.shape

(2, 2)

In [19]:
z = np.array([[1, 2, 4],
             [-1, 0, 1]])

In [20]:
print(z)

[[ 1  2  4]
 [-1  0  1]]


### 3D ARRAY

In [21]:
x = np.array(
    [[[1 ,2, 3],
      [4, 5, 6]],

     [[-1, -2, -3],
      [-4, -5, -6]]]
    )

In [22]:
print(x)

[[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]]


In [23]:
x.ndim

3

In [24]:
x.shape

(2, 2, 3)

### TYPY DANYCH

In [25]:
A = np.array([1, 2, 3])

In [26]:
A.dtype

dtype('int64')

In [27]:
A = np.array([1, 2, 3], dtype="float")

In [28]:
A.dtype

dtype('float64')

In [29]:
a = np.array([True, False])

In [30]:
a.dtype

dtype('bool')

### TWORZENIE TABLIC

In [31]:
zero = np.zeros(shape=(4,10), dtype="int")

In [32]:
print(zero)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [33]:
one = np.ones(shape=(5,5), dtype='int')

In [34]:
print(one)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [35]:
full = np.full(shape=(3, 3), fill_value=4, dtype='int')

In [36]:
print(full)

[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [37]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [39]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [40]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [41]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [42]:
np.linspace(start=0, stop=1, num=1)

array([0.])

In [43]:
np.linspace(start=0, stop=1, num=2)

array([0., 1.])

In [44]:
A = np.arange(15)

In [45]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [46]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [47]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### PODSTAWOWE OPERACJE NA TABLICACH

In [48]:
a = np.array([3, 1, 4, 2])

In [49]:
b = np.array([3, -1, 3, 2])

In [50]:
print (a, b)

[3 1 4 2] [ 3 -1  3  2]


In [51]:
a+b

array([6, 0, 7, 4])

In [52]:
a-b

array([0, 2, 1, 0])

In [53]:
a*b

array([ 9, -1, 12,  4])

In [54]:
a/b

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [55]:
a+3

array([6, 4, 7, 5])

In [56]:
np.add(a,b)

array([6, 0, 7, 4])

In [57]:
np.subtract(a,b)

array([0, 2, 1, 0])

In [58]:
np.multiply(a,b)

array([ 9, -1, 12,  4])

In [59]:
np.divide(a,b)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [60]:
X = np.array([[1, 3],
              [-2, 0]])
Y = np.array([[6, 0],
              [-1, 2]])

In [61]:
X*Y

array([[6, 0],
       [2, 0]])

In [62]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [63]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [64]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [65]:
X @ Y

array([[  3,   6],
       [-12,   0]])

### GENEROWANIE LICZB PSEUDOLOSOWYCH

In [66]:
np.random.seed(0)
'''
ziarno losowań - ważne przy pseudolosowych
'''

'\nziarno losowań - ważne przy pseudolosowych\n'

In [67]:
np.random.randn()

1.764052345967664

In [68]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [69]:
np.random.randn(5,4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743]])

In [70]:
np.random.rand()

0.359507900573786

In [71]:
np.random.rand(10)

array([0.43703195, 0.6976312 , 0.06022547, 0.66676672, 0.67063787,
       0.21038256, 0.1289263 , 0.31542835, 0.36371077, 0.57019677])

In [72]:
np.random.rand(5,4)

array([[0.43860151, 0.98837384, 0.10204481, 0.20887676],
       [0.16130952, 0.65310833, 0.2532916 , 0.46631077],
       [0.24442559, 0.15896958, 0.11037514, 0.65632959],
       [0.13818295, 0.19658236, 0.36872517, 0.82099323],
       [0.09710128, 0.83794491, 0.09609841, 0.97645947]])

In [73]:
np.random.randint(10)

2

In [74]:
np.random.randint(low=1, high=101)

43

In [75]:
np.random.choice([4,10,15,26,10])

4

In [76]:
np.random.choice(['python','sql','java'])

'sql'

In [77]:
data = np.arange(10)

In [78]:
np.random.shuffle(data)

In [79]:
print(data)

[8 1 4 5 6 3 7 2 0 9]


### PODSTAWOWE FUNKCJE

In [80]:
np.exp(1)

2.718281828459045

In [81]:
np.sqrt(9)

3.0

In [82]:
np.all([2, 3, 1])

True

In [83]:
np.any([1, 0, 0])

True

In [84]:
bool(1.3)

True

In [90]:
A = np.random.rand(5)
A

array([0.18319136, 0.58651293, 0.02010755, 0.82894003, 0.00469548])

In [91]:
np.argmax(A)

3

In [92]:
A[np.argmax(A)]

0.8289400292173631

In [93]:
np.argmin(A)

4

In [94]:
A[np.argmin(A)]

0.004695476192547066

In [95]:
np.argsort(A)

array([4, 2, 0, 1, 3])

In [96]:
np.max(A)

0.8289400292173631

In [97]:
np.min(A)

0.004695476192547066

In [98]:
np.mean(A)

0.32468946968292073

In [99]:
np.median(A)

0.18319136200711683

In [100]:
np.std(A)

0.32802688065093616

### INDEKSOWANIE, WYCINANIE

In [101]:
A = np.arange(20)

In [102]:
# A[idx], A[start:stop], A[:stop], A[stop:]

In [104]:
A[2]

2

In [105]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [106]:
A[:2]

array([0, 1])

In [107]:
A[[0, 2]]

array([0, 2])

In [108]:
A[-1]

19

In [109]:
A[10:15]

array([10, 11, 12, 13, 14])

In [112]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [113]:
A[0]

array([0, 1, 2, 3, 4])

In [114]:
A[1]

array([5, 6, 7, 8, 9])

In [115]:
A[:, 0]

array([ 0,  5, 10, 15])

In [116]:
A[1, 3]

8

In [118]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [121]:
A[1, 2] = 14

In [122]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### ITERACJA PO TABLICACH

In [124]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [130]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [131]:
for elem in A.flat:
  print(elem)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


### ZMIANA ROZMIARU TABLIC

In [133]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [134]:
A.shape

(4, 5)

In [135]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [136]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [139]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

### MASKI LOGICZNE

In [145]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [146]:
  A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [147]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [149]:
np.bitwise_and(A > -5, a < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [150]:
A[np.bitwise_and(A > -5, a < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5])

In [151]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [152]:
A[np.bitwise_or(A < -5, A > 5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])